# .streamlit/secrets.toml — PRZYKŁAD (skopiuj i zmień)
[auth]
cookie_name = "tmiv_auth"
cookie_key = "ULTRA-SECRET-CHANGE-ME"   # zmień na silny losowy
cookie_expiry_days = 7

# Wspierane konta (email jako login). Hasła muszą być zhashowane (bcrypt).
emails = ["admin@example.com", "mateusz@example.com"]
names  = ["Admin", "Mateusz"]           # opcjonalnie; jeśli brak, użyje e‑maili
hashed_passwords = [
  # Uwaga: to PRZYKŁADOWY hash hasła "Passw0rd!" — nie używaj go na produkcji.
  "$2b$12$k7j1FH5m1kGmE1P8lO8X8e6Y0B1vSx3o2r7f2t8u9w0x1y2z3a4bC",
  "$2b$12$k7j1FH5m1kGmE1P8lO8X8e6Y0B1vSx3o2r7f2t8u9w0x1y2z3a4bC"
]
